### student marks prediction

### Data collection

In [1]:
import pandas as pd
student_marks=pd.read_csv("student marks.csv",sep='\t')
student_marks.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

## initialative analysis

In [10]:
student_marks.shape

(100, 3)

In [8]:
student_marks.isnull().sum()

number_courses    0
time_study        0
Marks             0
dtype: int64

In [6]:
student_marks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number_courses  100 non-null    int64
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

## data understanding

### about the dataset:
 ""Number of rows is 0 to 100,mean(average of courses,study_time,marks)=5,4,24 and max=55,min=5 then ,median=20,important thing about the dataset is looks it that percentage""

In [2]:
student_marks.describe()

       number_courses  time_study       Marks
count      100.000000  100.000000  100.000000
mean         5.290000    4.077140   24.417690
std          1.799523    2.372914   14.326199
min          3.000000    0.096000    5.609000
25%          4.000000    2.058500   12.633000
50%          5.000000    4.022000   20.059500
75%          7.000000    6.179250   36.676250
max          8.000000    7.957000   55.299000

### find the relationship  by using correlation

In [8]:
student_marks.corr()

                number_courses  time_study     Marks
number_courses        1.000000    0.204844  0.417335
time_study            0.204844    1.000000  0.942254
Marks                 0.417335    0.942254  1.000000

### To build the model

In [3]:
from sklearn.model_selection import train_test_split

x = student_marks[['number_courses','time_study']]
y = student_marks[['Marks']]
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

### To train the model

In [4]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9459936100591213

### model understanding

In [5]:
model.coef_
model.intercept_

array([-6.61304673])

### model testing (PREDICTION)

In [6]:
model.predict([[5,4]])

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[23.42418975]])

### save my trained model

In [7]:
import joblib
joblib.dump(model,"linear_model.pkl")

['linear_model.pkl']